extends Node

const HEAT_BASE_MAX := 100.0
const HEAT_TRIGGER_THRESHOLD := 100.0
const HEAT_HIT := 2.0
const HEAT_KILL_NORMAL := 5.0
const HEAT_KILL_ELITE := 15.0
const HEAT_KILL_BOSS := 50.0
const HEAT_DAMAGED := 5.0

const UNFOLD_CONSUME_RATE := 5.0
const UNFOLD_TRANSITION_IN := 0.5
const UNFOLD_COLLAPSE_TIME := 0.3
const UNFOLD_COOLDOWN_NORMAL := 1.5
const UNFOLD_COOLDOWN_COLLAPSE := 3.0

const PERMADEATH_BASE := 0.12
const RISK_UNFOLD_FULL := 0.005
const RISK_UNFOLD_EARLY := 0.002
const RISK_COLLAPSE := 0.01
const RISK_CAP_PER_RUN := 0.04

const CORRUPTION_THRESHOLD_YELLOW := 5.0
const CORRUPTION_THRESHOLD_RED := 10.0
const CORRUPTION_UNFOLD_FULL := 1.0
const CORRUPTION_UNFOLD_EARLY := 0.5
const CORRUPTION_COLLAPSE := 2.0

const PLAYER_MAX_HP := 10
const PLAYER_DASH_INVULN := 0.2
const PLAYER_HIT_INVULN := 0.5

